/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tecnicassimulacion;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Dvid
 */
public class ModeloA extends javax.swing.JFrame {

                   

    JComboBox combo = new JComboBox();
    String F1 = "Utilizacion promedio del sistema";
    String F2 = "Probabilidad de que N clientes esten en el sistema";
    String F3 = "Numero promedio de clientes en el sistema de servicio";
    String F4 = "Numero promedio de clientes en la fila de espera";
    String F5 = "Tiempo promedio transcurrido en el sistema, incluido el servicio";
    String F6 = "Tiempo promedio de espera en la fila";

    Icon iF1 = new ImageIcon(getClass().getResource("/Imagenes/MAf1.PNG"));
    Icon iF2 = new ImageIcon(getClass().getResource("/Imagenes/MAf2.PNG"));
    Icon iF3 = new ImageIcon(getClass().getResource("/Imagenes/MAf3.PNG"));
    Icon iF4 = new ImageIcon(getClass().getResource("/Imagenes/MAf4.PNG"));
    Icon iF5 = new ImageIcon(getClass().getResource("/Imagenes/MAf5.PNG"));
    Icon iF6 = new ImageIcon(getClass().getResource("/Imagenes/MAf6.PNG"));
String a;    
    /**
     * Creates new form ModeloA
     */
    public ModeloA() {
        initComponents();
        setLocationRelativeTo(null);
        jComboBox1.addItem("Seleccione una opcion");
        jComboBox1.addItem(F1);
        jComboBox1.addItem(F2);
        jComboBox1.addItem(F3);
        jComboBox1.addItem(F4);
        jComboBox1.addItem(F5);
        jComboBox1.addItem(F6);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CALCULO DE FORMULAS MODELO A");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Seleccione lo que desea calcular:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String datos = (String) jComboBox1.getSelectedItem();
        if (datos.equals(F1)) {
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO A ", WIDTH, iF1, null, "");
            String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO A ", WIDTH, iF1, null, "");
            if (landa != null && mu != null) {

                double vlanda = Double.valueOf(landa);
                double vmu = Double.valueOf(mu);
                double p = vlanda / vmu;

                JOptionPane.showMessageDialog(null, "El promedio del sistema es = " + p);
            }
        }
        if (datos.equals(F2)) {
            String n = (String) JOptionPane.showInputDialog(null, "Ingrese valor de N", "MODELO A ", WIDTH, iF2, null, "");
            String p = (String) JOptionPane.showInputDialog(null, "Ingrese valor de P", "MODELO A ", WIDTH, iF2, null, "");
            if (n != null && p != null) {
                double vn = Double.valueOf(n);
                double vp = Double.valueOf(p);
                double pn = (1 - vp) * Math.pow(vp, vn);

                JOptionPane.showMessageDialog(null, "La probabilidad de cliente es = " + pn);
            }
        }
        if (datos.equals(F3)) {
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO A ", WIDTH, iF3, null, "");
            String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO A ", WIDTH, iF3, null, "");
            if (landa != null && mu != null) {

                double vlanda = Double.valueOf(landa);
                double vmu = Double.valueOf(mu);
                double l = vlanda / (vmu - vlanda);

                JOptionPane.showMessageDialog(null, "Numero promedio de clientes en el sistema de servicio = " + l);
            }
        }
        if (datos.equals(F4)) {
            String p = (String) JOptionPane.showInputDialog(null, "Ingrese valor de P", "MODELO A ", WIDTH, iF4, null, "");
            String l = (String) JOptionPane.showInputDialog(null, "Ingrese valor de L", "MODELO A ", WIDTH, iF4, null, "");
            if (p != null && l != null) {

                double vp = Double.valueOf(p);
                double vl = Double.valueOf(l);
                double lq = vp * vl;

                JOptionPane.showMessageDialog(null, "Numero prom. de clientes en la fila de espera = " + lq);
            }
        }
        if (datos.equals(F5)) {
            String mu = (String) JOptionPane.showInputDialog(null, "Ingrese valor de μ", "MODELO A ", WIDTH, iF5, null, "");
            String landa = (String) JOptionPane.showInputDialog(null, "Ingrese valor de λ", "MODELO A ", WIDTH, iF5, null, "");

            if (mu != null && landa != null) {
                double vmu = Double.valueOf(mu);
                double vlanda = Double.valueOf(landa);
                double w = 1 / (vmu - vlanda);

                JOptionPane.showMessageDialog(null, "Tiempo prom. transcurrido en el sistema, incluido el servicio = " + w);
            }
        }
        if (datos.equals(F6)) {
            String p = (String) JOptionPane.showInputDialog(null, "Ingrese valor de P", "MODELO A ", WIDTH, iF6, null, "");
            String w = (String) JOptionPane.showInputDialog(null, "Ingrese valor de W", "MODELO A ", WIDTH, iF6, null, "");
            if (p != null && w != null) {
                double vp = Double.valueOf(p);
                double vw = Double.valueOf(w);
                double wq = vp * vw;

                JOptionPane.showMessageDialog(null, "Tiempo prom. en la fila de espera = " + wq);

            }
        }


    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModeloA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModeloA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModeloA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModeloA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModeloA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
